export {default as CategoryAllPaths} from './all-paths'
export {default as CategoryPopularPaths} from './popular-paths'
export {default as CategorySearch} from './search'
export {default as CategorySinglePage} from './category-single'
export {default as CategoryDropdown} from './category-dropdown'
